Update contributors.js
AbhayVAshokan/Hack-NASA-using-HTML pull request #52
Opened 2021-10-29 18:21 UTC by bottercode

2021-10-29 18:54 UTC, AbhayVAshokan requested changes

2021-10-29 18:54 UTC, AbhayVAshokan commented on src/contributors.js
> +export const PSathyaNarayan = {
Please change the variable name to yours.

2021-10-30 06:33 UTC, bottercode reviewed
done

2021-10-30 07:09 UTC, AbhayVAshokan requested changes

2021-10-30 07:09 UTC, AbhayVAshokan commented on src/contributors.js
> +  username: "port ghost"
One more change. Sorry I missed this earlier.  Change it to your GitHub id "bottercode". Click the preview link posted by Netlify above. It currently shows undefined below your name.

2021-10-31 04:59 UTC, bottercode reviewed
done

2021-10-31 05:08 UTC, merged